CREATE TABLE IF NOT EXISTS `player_bag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `player_id` BIGINT UNSIGNED NOT NULL COMMENT '玩家ID，关联player.id',
  `item_id` BIGINT UNSIGNED NOT NULL COMMENT '道具ID',
  `item_name` VARCHAR(100) NOT NULL COMMENT '道具名称',
  `item_type` VARCHAR(50) NOT NULL COMMENT '道具类型',
  `quantity` INT NOT NULL DEFAULT 1 COMMENT '道具数量',
  `expire_time` DATETIME DEFAULT NULL COMMENT '过期时间（如有时效）',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='玩家背包道具表';
