CREATE TABLE IF NOT EXISTS `player` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩家ID',
  `username` VARCHAR(50) NOT NULL COMMENT '登录账号',
  `password` VARCHAR(100) NOT NULL COMMENT '密码（加密后）',
  `nickname` VARCHAR(50) NOT NULL COMMENT '玩家昵称',
  `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
  `level` INT NOT NULL DEFAULT 1 COMMENT '等级',
  `exp` BIGINT NOT NULL DEFAULT 0 COMMENT '经验值',
  `gold` BIGINT NOT NULL DEFAULT 0 COMMENT '金币',
  `diamond` BIGINT NOT NULL DEFAULT 0 COMMENT '钻石',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1正常 0禁用',
  `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='玩家基础信息表';
